[feat] CompleteViewModel 테스트 코드 작성
kotlinx.serialization.MissingFieldException: Fields [bandalartId, bandalartTitle, bandalartProfileEmoji, bandalartChartImageUri] are required for type with serial name 'com.nexters.bandalart.core.navigation.Route.Complete', but they were missing
관련 이슈를 해결 해야함